### ISSUE TITLE
App Rejected

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/repositories-manager#5]
Sorry, unfortunately we've decided not to publish your app in AppCenter due to the security and stability implications of modifying software sources.

**Comment by unbelievableflavour** [comment]
I understand. Anything i can do to make it safer to still get published?

**Comment by cassidyjames** [comment]
Unfortunately, it's a fairly fundamental issue with this type of app. To help avoid a similar situation in the future, we will be modifying our AppCenter publishing guidelines to let developers know that these types of apps will not be published. Thank you for your time, and we hope to see future apps from you published in AppCenter!

**Comment by unbelievableflavour** [comment]
Ok, no problem!
