### ISSUE TITLE
Make a reference to this app in your other projects

### ISSUE THREAD

**Issue by zvirdaniel** [bartzaalberg/repositories-manager#6]
Hi,

it is sad that this app was not allowed in the AppStore, because something like this is greatly appreciated by anyone who understands PPA's. So maybe, you could add a link to the end of your other projects here on GitHub? And state that this app is complete, but will not be allowed in the AppStore in the README.md of this project?

Seriously, I have been looking for something like this for quite some time. I really appreciate it. :+1:

**Comment by unbelievableflavour** [comment]
Well actually it's not done. It's a bit rough around the edges. I will fix some final things and then will probably add a line the readme's.

**Comment by zvirdaniel** [comment]
Okay, I just wanted to say, that without any propagation at all, this app will be hard to find.
